export const orders = [
  {
    id: 1,
    date: "May 5, 4:20 PM",
    fullName: "Tom Anderson",
    status: "Оплаченный",
    orderStatus: "Готовый",
    totalPrice: "49.9}",
  },
  {
    id: 2,
    date: "May 5, 4:15 PM",
    fullName: "Jayden Walker",
    status: "Оплаченный",
    orderStatus: "Готовый",
    totalPrice: "34.36",
  },
  {
    id: 3,
    date: "May 5, 4:15 PM",
    fullName: "Inez Kim",
    status: "Оплаченный",
    orderStatus: "Готовый",
    totalPrice: "5.51",
  },
  {
    id: 4,
    date: "May 5, 4:12 PM",
    fullName: "Francisco Henry",
    status: "Оплаченный",
    orderStatus: "Отправленный",
    totalPrice: "29.74",
  },
  {
    id: 5,
    date: "May 5, 4:12 PM",
    fullName: "Violet Phillips",
    status: "Оплаченный",
    orderStatus: "Отправленный",
    totalPrice: "23.06",
  },
  {
    id: 6,
    date: "May 5, 4:12 PM",
    fullName: "Rosetta Becker",
    status: "Оплаченный",
    orderStatus: "Отправленный",
    totalPrice: "87.44",
  },
  {
    id: 7,
    date: "May 5, 4:10 PM",
    fullName: "Dean Love",
    status: "Оплаченный",
    orderStatus: "Готовый",
    totalPrice: "44.55",
  },
  {
    id: 8,
    date: "May 5, 4:08 PM",
    fullName: "Nettie Tyler",
    status: "Оплаченный",
    orderStatus: "Готовый",
    totalPrice: "36.79",
  },
  {
    id: 9,
    date: "May 5, 4:04 PM",
    fullName: "Miguel Harris",
    status: "В ожидании",
    orderStatus: "Готовый",
    totalPrice: "50.54",
  },
  {
    id: 10,
    date: "May 5, 4:04 PM",
    fullName: "Angel Conner",
    status: "В ожидании",
    orderStatus: "Готовый",
    totalPrice: "63.47",
  },
  {
    id: 11,
    date: "May 5, 4:03 PM",
    fullName: "Rosalie Singleton",
    status: "В ожидании",
    orderStatus: "Полученный",
    totalPrice: "91.63",
  },
];
